---
title: "Traitement_Final"
author: "Julien Monnot & Christophe Benavent"
date: "15/06/2021"
output: html_document
---
```{r setup, include=FALSE}
#vect_prez <- c("Givenchy","Chanel","Dior","Cartier","LouisVuitton")
vect_ <- "Michelin"

####PACKAGE STORAGE
library(quanteda)
library(dplyr)
library(tm)
library(stringr)
library(udpipe)
library(syuzhet)
library(seededlda)
library(tidyr)
library(tibble)
library(forcats)
library(ggplot2)
library(tidylo)

df_trt <- readRDS("Data_primaires.rds")

table(df_trt$Marque)

df_ind <- df_trt %>%
  filter(Marque%in%vect_) %>%
  select(status_id,screen_name,text,Marque)

```


```{r annotation}
#udpipe_download_model("french")

udmodel <- udpipe_load_model("french-gsd-ud-2.5-191206.udpipe")

annot_ud <- udpipe_annotate(udmodel,df_ind$text, doc_id = df_ind$status_id)

annot_ud <- as.data.frame(annot_ud)

names(annot_ud)[names(annot_ud) == "doc_id"] <- "status_id"

df_trt_annot <- left_join(annot_ud,df_ind)

saveRDS(df_trt_annot,"df_prez_dior.rds")
```



```{r filtering, echo=FALSE}
#df_trt_annot <- readRDS("df_prez_luxe.rds")
annot_t <- df_trt_annot %>%
  filter(upos=="ADJ")

foo <- annot_t%>%mutate(Off_Acc=ifelse(str_detect(lemma,"@.*")==TRUE,"TRUE",
                                       ifelse(str_detect(lemma,"http.*")==TRUE,"TRUE",                                     ifelse(str_detect(lemma,"michel*")==TRUE,"TRUE",
ifelse(str_detect(lemma,"&.*")==TRUE,"TRUE",
                                "FALSE")))))
foo <- foo %>%
  filter(Off_Acc!="TRUE")

foo <- foo %>%
  mutate(ncr = nchar(lemma)) %>%
  filter(ncr>2)
```
min 0.0001 max 0.1
```{r cars}
mydfm <- dfm(foo$lemma,
             tolower = TRUE,
             what = "word")

#             groups = foo$Marque)
mydfm@Dimnames$features

mydfm.un.trim <-
  dfm_trim(
    mydfm,
min_termfreq = 0.0003,
max_termfreq = 0.01,
termfreq_type ="prop")

```

```{r cars_2}
#dict <- dictionary("C:/Users/jmonn/Documents/GitHub/Personnalite/adjectifs de marque.xlsx")
dict_brut <- readxl::read_excel("C:/Users/jmonn/Documents/GitHub/Personnalite/adjectifs de marque.xlsx")

vect_cat <- as.factor(dict_brut$`Facteur Ocean`)
vect_cat <- levels(vect_cat)
dict_net <- c()

for (val in vect_cat) {
  foo <- dict_brut%>%filter(`Facteur Ocean`==val)
  a <- foo$`Pré-Régex`
  dict_net[[val]] <- a
  }
dict_net <- dictionary(dict_net)
```

```{r cars_3}

lda <- textmodel_seededlda(
  mydfm.un.trim,
  dict_net,
  valuetype = "regex",
  max_iter = 2000,
  residual = TRUE,
  min_termfreq=2,
  alpha = NULL,
  beta = NULL,
)

terms(lda)
topics(lda)

```


